In [1]:
import numpy as np
import pandas as pd
import plotly.express as px
import plotly
import json
import datetime as dt
import matplotlib.dates as mdates
import unidecode
from IPython.display import Image
from PIL import Image, ImageDraw
#import imageio
from get_data import read_data, get_data
import plotly.graph_objects as go

df = read_data(pd.read_csv('Dados_indiv_MRJ_covid19 (2).csv', encoding = 'iso-8859-1', delimiter = ';'), fonte='prefeitura')
dt_start = '15-03-2020'
dt_fim = '15-05-2020'
bairros = df['Bairro'].unique()
dic_acumulados = {}
dic_novos = {}

for b in bairros:
    if b != 'FORA DO MUNICÍPIO' and b != 'INDEFINIDO':
        dic_acumulados.update({b:get_data(local = b, df = df,fonte = 'prefeitura', 
                                T_start = dt_start, T_fim = dt_fim, to_print=False)[0]})
        dic_novos.update({b:get_data(local = b, df = df,fonte = 'prefeitura', 
                                T_start = dt_start, T_fim = dt_fim, to_print=False)[1]})
            
data_start = dt_start
data_end = dt_fim
start = dt.datetime.strptime(data_start, "%d-%m-%Y")
then = dt.datetime.strptime(data_end, "%d-%m-%Y")
days = mdates.drange(start,then,dt.timedelta(days=1))
dias = [str(mdates.num2date(v)).split(' ')[0] for v in days]

dic_acumulados.update({'Datas':dias})
dic_novos.update({'Datas':dias})

df_series_temp_acumulados = pd.DataFrame(dic_acumulados)
df_series_temp_novos = pd.DataFrame(dic_novos)

df_series_temp_acumulados.to_csv('dados-series-temp-acumul-bairros.csv')
df_series_temp_novos.to_csv('dados-series-temp-novos-bairros.csv')

In [2]:
df

,Data,Bairro,AP Residência,Faixa Etaria,Situação atual,Data_atualização
0,06/05/2020,TIJUCA,2.2,De 80 a 89,óbito,15/05/2020
1,08/04/2020,LARANJEIRAS,2.1,De 80 a 89,óbito,15/05/2020
2,30/04/2020,BOTAFOGO,2.1,De 90 a 100,óbito,15/05/2020
3,24/04/2020,JARDIM GUANABARA,3.1,De 80 a 89,óbito,15/05/2020
4,17/04/2020,CACHAMBI,3.2,De 60 a 69,óbito,15/05/2020
...,...,...,...,...,...,...
11709,07/04/2020,BOTAFOGO,2.1,De 30 a 39,recuperado,15/05/2020
11710,14/04/2020,BARRA DA TIJUCA,4.0,De 50 a 59,recuperado,15/05/2020
11711,08/05/2020,JACAREPAGUA,4.0,De 60 a 69,recuperado,15/05/2020
11712,08/04/2020,BOTAFOGO,2.1,De 80 a 89,recuperado,15/05/2020
11713,06/05/2020,TIJUCA,2.2,De 80 a 89,ativo,15/05/2020

In [3]:
df[df['Bairro'] == b]['AP Residência'].values[0][0]

'1'

In [4]:
bairros = df['Bairro'].unique()
aps = [[] for i in range(1,6)]
for b in bairros:
    if df[df['Bairro'] == b]['AP Residência'].values[0][0] == '1':
        aps[0] += [b]
        
    if df[df['Bairro'] == b]['AP Residência'].values[0][0] == '2':
        aps[1] += [b]
        
    if df[df['Bairro'] == b]['AP Residência'].values[0][0] == '3':
        aps[2] += [b]
        
    if df[df['Bairro'] == b]['AP Residência'].values[0][0] == '4':
        aps[3] += [b]
        
    if df[df['Bairro'] == b]['AP Residência'].values[0][0] == '5':
        aps[4] += [b]

In [5]:
np.sum(np.array([[1,2,3],[1,2,3]]), axis = 0)

array([2, 4, 6])

In [6]:
df = read_data(pd.read_csv('Dados_indiv_MRJ_covid19 (2).csv', encoding = 'iso-8859-1', delimiter = ';'), fonte='prefeitura')
dt_start = '15-03-2020'
dt_fim = '15-05-2020'
dic_acumulados_aps = {}
dic_novos_aps = {}

for i, ap in enumerate(aps):
    if ap != 'N/D':
        dic_acumulados_aps.update({f'AP %s' %(i+1):np.sum(np.array([get_data(local = b, df = df,fonte = 'prefeitura', 
                                T_start = dt_start, T_fim = dt_fim, to_print=False)[0] for b in ap]), axis = 0)})
        dic_novos_aps.update({f'AP %s' %(i+1):np.sum(np.array([get_data(local = b, df = df,fonte = 'prefeitura', 
                                T_start = dt_start, T_fim = dt_fim, to_print=False)[1] for b in ap]), axis = 0)})
            
start = dt.datetime.strptime(dt_start, "%d-%m-%Y")
then = dt.datetime.strptime(dt_fim, "%d-%m-%Y")
days = mdates.drange(start,then,dt.timedelta(days=1))
dias = [str(mdates.num2date(v)).split(' ')[0] for v in days]

dic_acumulados_aps.update({'Datas':dias})
dic_novos_aps.update({'Datas':dias})

df_series_temp_acumulados_aps = pd.DataFrame(dic_acumulados_aps)
df_series_temp_novos_aps = pd.DataFrame(dic_novos_aps)

df_series_temp_acumulados_aps.to_csv('dados-series-temp-acumul-aps.csv')
df_series_temp_novos_aps.to_csv('dados-series-temp-novos-aps.csv')

In [7]:
df_series_temp_acumulados_aps

    AP 1  AP 2  AP 3  AP 4  AP 5       Datas
0      3    46    62    23    30  2020-03-15
1      3    48    62    23    30  2020-03-16
2      3    49    64    23    31  2020-03-17
3      3    52    66    23    31  2020-03-18
4      3    55    69    24    31  2020-03-19
..   ...   ...   ...   ...   ...         ...
56   365  2341  2444  1197  1439  2020-05-10
57   372  2395  2481  1228  1459  2020-05-11
58   396  2482  2579  1289  1496  2020-05-12
59   420  2568  2747  1347  1584  2020-05-13
60   434  2655  2872  1401  1646  2020-05-14

[61 rows x 6 columns]

## Bairros

In [8]:
media_movel_novos = []
media_movel_acumulados = []
for col in df_series_temp_novos.columns[:-1]:
    temp_df_novos = df_series_temp_novos[col].values
    temp_df_acumulados = df_series_temp_acumulados[col].values
    media_movel_novos_b = []
    media_movel_acumulados_b = []
    for i in range(len(temp_df_novos)-2):
        if i < 5:
            media_movel_novos_b += [np.sum(temp_df_novos[:i+2])/(6*temp_df_acumulados[-1])]
            media_movel_acumulados_b += [np.sum(temp_df_acumulados[:i+2])/(6*temp_df_acumulados[-1])]
        else:
            media_movel_novos_b += [np.sum(temp_df_novos[i-4:i+2])/(6*temp_df_acumulados[-1])]
            media_movel_acumulados_b += [np.sum(temp_df_acumulados[i-4:i+2])/(6*temp_df_acumulados[-1])]
    media_movel_novos += [media_movel_novos_b]
    media_movel_acumulados += [media_movel_acumulados_b]

## APs

In [9]:
media_movel_novos_aps = []
media_movel_acumulados_aps = []
for col in df_series_temp_novos_aps.columns[:-1]:
    temp_df_novos_aps = df_series_temp_novos_aps[col].values
    temp_df_acumulados_aps = df_series_temp_acumulados_aps[col].values
    media_movel_novos_aps_ap = []
    media_movel_acumulados_aps_ap = []
    for i in range(len(temp_df_novos_aps)-2):
        if i < 5:
            media_movel_novos_aps_ap += [np.sum(temp_df_novos_aps[:i+2])/(6*temp_df_acumulados_aps[-1])]
            media_movel_acumulados_aps_ap += [np.sum(temp_df_acumulados_aps[:i+2])/(6*temp_df_acumulados_aps[-1])]
        else:
            media_movel_novos_aps_ap += [np.sum(temp_df_novos_aps[i-4:i+2])/(6*temp_df_acumulados_aps[-1])]
            media_movel_acumulados_aps_ap += [np.sum(temp_df_acumulados_aps[i-4:i+2])/(6*temp_df_acumulados_aps[-1])]
    media_movel_novos_aps += [media_movel_novos_aps_ap]
    media_movel_acumulados_aps += [media_movel_acumulados_aps_ap]

In [10]:
len(media_movel_novos_aps), len(media_movel_novos)

(5, 160)

In [11]:
#Bairros
df_media_movel_novos = pd.DataFrame({col:media_movel_novos[i] for i, 
                                     col in enumerate(df_series_temp_novos.columns[:-1])})

df_media_movel_acumulados = pd.DataFrame({col:media_movel_acumulados[i] for i, 
                                          col in enumerate(df_series_temp_acumulados.columns[:-1])})
#APs
df_media_movel_novos_aps = pd.DataFrame({col:media_movel_novos_aps[i] for i, 
                                         col in enumerate(df_series_temp_novos_aps.columns[:-1])})

df_media_movel_acumulados_aps = pd.DataFrame({col:media_movel_acumulados_aps[i] for i, 
                                              col in enumerate(df_series_temp_acumulados_aps.columns[:-1])})

In [12]:
df_media_movel_novos['Datas'] = df_series_temp_novos['Datas']
df_media_movel_acumulados['Datas'] = df_series_temp_acumulados['Datas']
df_media_movel_novos_aps['Datas'] = df_series_temp_novos_aps['Datas']
df_media_movel_acumulados_aps['Datas'] = df_series_temp_acumulados_aps['Datas']

In [13]:
df_media_movel_acumulados_aps

        AP 1      AP 2      AP 3      AP 4      AP 5       Datas
0   0.002304  0.005901  0.007196  0.005472  0.006075  2020-03-15
1   0.003456  0.008977  0.010910  0.008208  0.009214  2020-03-16
2   0.004608  0.012241  0.014740  0.010945  0.012353  2020-03-17
3   0.005760  0.015694  0.018744  0.013800  0.015492  2020-03-18
4   0.006912  0.019523  0.022981  0.017012  0.018631  2020-03-19
5   0.006912  0.020465  0.023677  0.017606  0.018834  2020-03-20
6   0.006912  0.021281  0.024489  0.018320  0.019036  2020-03-21
7   0.007680  0.022913  0.025592  0.019629  0.019542  2020-03-22
8   0.008449  0.024733  0.026811  0.021294  0.020251  2020-03-23
9   0.009601  0.026868  0.028203  0.023198  0.021162  2020-03-24
10  0.010753  0.029253  0.029654  0.025815  0.022276  2020-03-25
11  0.013057  0.032706  0.032149  0.028789  0.023896  2020-03-26
12  0.016513  0.036974  0.035399  0.032239  0.025820  2020-03-27
13  0.019969  0.040866  0.038649  0.035451  0.027440  2020-03-28
14  0.024578  0.047269  0.043698  0.040328  0.029465  2020-03-29
15  0.030338  0.056372  0.049501  0.046395  0.032908  2020-03-30
16  0.037634  0.066290  0.057103  0.053057  0.037667  2020-03-31
17  0.045315  0.077024  0.065053  0.061504  0.043337  2020-04-01
18  0.053379  0.088638  0.073642  0.071497  0.050932  2020-04-02
19  0.061828  0.101067  0.082811  0.082441  0.059032  2020-04-03
20  0.069508  0.111488  0.090935  0.092196  0.067234  2020-04-04
21  0.077189  0.121720  0.101497  0.103022  0.076954  2020-04-05
22  0.086022  0.133145  0.112813  0.114561  0.088295  2020-04-06
23  0.094854  0.145888  0.125406  0.127171  0.102673  2020-04-07
24  0.106375  0.159950  0.139044  0.140614  0.117254  2020-04-08
25  0.118280  0.173697  0.153726  0.154295  0.133556  2020-04-09
26  0.131720  0.188198  0.169800  0.167975  0.151681  2020-04-10
27  0.145161  0.201381  0.184366  0.180942  0.169401  2020-04-11
28  0.159370  0.217389  0.201370  0.196407  0.189955  2020-04-12
29  0.175883  0.233271  0.219533  0.211159  0.211118  2020-04-13
30  0.196621  0.250345  0.238452  0.227576  0.233799  2020-04-14
31  0.218894  0.271814  0.259981  0.245182  0.257695  2020-04-15
32  0.243472  0.296234  0.283078  0.265525  0.284022  2020-04-16
33  0.268049  0.321155  0.305942  0.285153  0.309842  2020-04-17
34  0.289939  0.342561  0.325441  0.301570  0.332321  2020-04-18
35  0.315668  0.369052  0.347783  0.320604  0.356521  2020-04-19
36  0.335637  0.394288  0.369023  0.337140  0.378696  2020-04-20
37  0.357143  0.417828  0.389102  0.352605  0.400263  2020-04-21
38  0.377496  0.439109  0.408252  0.367119  0.419704  2020-04-22
39  0.401306  0.467294  0.433728  0.389484  0.444006  2020-04-23
40  0.426651  0.496798  0.459320  0.412443  0.468003  2020-04-24
41  0.445853  0.519711  0.479109  0.431002  0.486837  2020-04-25
42  0.471198  0.547395  0.504817  0.453486  0.511847  2020-04-26
43  0.498848  0.575392  0.532498  0.478587  0.539287  2020-04-27
44  0.528034  0.605210  0.563254  0.507019  0.570879  2020-04-28
45  0.557988  0.632203  0.592502  0.532715  0.603686  2020-04-29
46  0.587558  0.657439  0.620938  0.559481  0.636594  2020-04-30
47  0.618280  0.682235  0.649025  0.586962  0.668287  2020-05-01
48  0.641705  0.700063  0.669394  0.609684  0.692689  2020-05-02
49  0.662058  0.718330  0.688603  0.632762  0.715776  2020-05-03
50  0.684332  0.736723  0.705896  0.655008  0.736938  2020-05-04
51  0.705837  0.754551  0.721506  0.676778  0.753949  2020-05-05
52  0.730415  0.774011  0.740889  0.703545  0.773086  2020-05-06
53  0.756528  0.796736  0.765378  0.736855  0.796476  2020-05-07
54  0.781490  0.820716  0.790332  0.770283  0.820069  2020-05-08
55  0.804147  0.841620  0.811746  0.799548  0.840117  2020-05-09
56  0.822965  0.861645  0.831128  0.827385  0.857128  2020-05-10
57  0.846006  0.881419  0.851265  0.856650  0.873734  2020-05-11
58  0.873272  0.903453  0.876161  0.884487  0.894694  2020-05-12

In [14]:
data_novos = []
data_acumulados = []
for i, col in enumerate(df_media_movel_novos.columns[:-1]):
    data_novos += [go.Scatter(x = df_media_movel_novos['Datas'], 
                              y = df_media_movel_novos[col].values, name = col)]
    
    data_acumulados += [go.Scatter(x = df_media_movel_acumulados['Datas'], 
                                   y = df_media_movel_acumulados[col].values, name = col, visible = False)]
data = data_novos + data_acumulados

In [15]:
data_novos_aps = []
data_acumulados_aps = []
for i, col in enumerate(df_media_movel_novos_aps.columns[:-1]):
    data_novos_aps += [go.Scatter(x = df_media_movel_novos_aps['Datas'], 
                              y = df_media_movel_novos_aps[col].values, name = col)]
    
    data_acumulados_aps += [go.Scatter(x = df_media_movel_acumulados_aps['Datas'], 
                                   y = df_media_movel_acumulados_aps[col].values, name = col, visible = False)]
data_aps = data_novos_aps + data_acumulados_aps

In [16]:
len(data_aps)

10

In [17]:
updatemenus = list([
                    dict(active = 0,
                                buttons = list([
                                    dict(label = 'Novos',
                                        method = 'update', 
                                        args = [{'visible':  [ j//(len(data)//2) == 0 for j in range(len(data))] },
                                              {'title': 'Médias móveis por bairros: casos <b> novos </b> <br> do dia 15/03 até 12/05'}
                                              ]),
                                    dict(label = 'Acumulados',
                                        method = 'update', 
                                        args = [{'visible':  [ j//(len(data)//2)  == 1 for j in range(len(data))] },
                                              {'title': 'Médias móveis por bairros: casos <b> acumulados </b> <br> do dia 15/03 até 12/05'}
                                              ]),
                                    ])) ])


updatemenus_aps = list([
                    dict(active = 0,
                                buttons = list([
                                    dict(label = 'Novos',
                                        method = 'update', 
                                        args = [{'visible':  [ j//(len(data_aps)//2) == 0 for j in range(len(data_aps))] },
                                              {'title': 'Médias móveis por APs: casos <b> novos </b> <br> do dia 15/03 até 12/05'}
                                              ]),
                                    dict(label = 'Acumulados',
                                        method = 'update', 
                                        args = [{'visible':  [ j//(len(data_aps)//2)  == 1 for j in range(len(data_aps))] },
                                              {'title': 'Médias móveis por APs: casos <b> acumulados </b> <br> do dia 15/03 até 12/05'}
                                              ]),
                                    ])) ])

In [18]:
fig = go.Figure(data = data)
fig['layout']['updatemenus'] = updatemenus
fig['layout']['title']['x'] = 0.5
fig['layout']['title']['text'] = 'Médias móveis por bairros: casos <b> novos </b> <br> do dia 15/03 até 12/05'

In [19]:
#fig.show()

In [20]:
with open("media_movel_bairros_2-4.html", "w") as f:
    f.write(fig.to_html())

In [21]:
fig2 = go.Figure(data = data_aps)
fig2['layout']['updatemenus'] = updatemenus_aps
fig2['layout']['title']['x'] = 0.5
fig2['layout']['title']['text'] = 'Médias móveis por bairros: casos <b> novos </b> <br> do dia 15/03 até 12/05'

In [22]:
#fig2.show()

In [23]:
with open("media_movel_aps_2-4.html", "w") as f:
    f.write(fig2.to_html())